import type { Metadata } from "next";
import { ModeToggle, ThemeProvider } from "@/components/theme";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased grid h-screen grid-rows-[auto,1fr,auto]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="border-b">
            <header className="max-w-4xl mx-auto px-2 py-4 flex justify-between">
              <h1 className="text-2xl font-semibold tracking-tighter">Chat</h1>
              <ModeToggle />
            </header>
          </div>
          {children}
          <div className="text-center py-2 text-xs text-foreground/50 border-t">
            Made by{" "}
            <a
              href="https://github.com/deon-gracias"
              className="font-medium text-foreground/80 underline cursor-pointer"
            >
              Deon Gracias
            </a>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
